trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'   
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    VERSION=$(date +%Y.%m.%d.%H%M)
    echo "##vso[task.setvariable variable=VersionNumber]$VERSION"
    echo "Generated Version: $VERSION"
  displayName: 'Generate Build Version'

- script: dotnet restore ./MyHelloWorld/MyHelloWorld.csproj
  displayName: 'Restore Dependencies'

- script: dotnet build ./MyHelloWorld/MyHelloWorld.csproj --configuration Release -p:Version=$(VersionNumber)
  displayName: 'Build the Project'

- script: dotnet test ./MyHelloWorld/MyHelloWorld.csproj
  displayName: 'Run Tests'

- script: dotnet pack ./MyHelloWorld/MyHelloWorld.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Package the Project'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact to Azure DevOps'
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'drop'
