trigger:
- main  

pool:
  name: Default  

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet build --configuration Release
  displayName: 'Build the Project'

- script: dotnet test
  displayName: 'Run Tests'

- script: dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Package the Project'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact to Azure DevOps'
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'drop'
