trigger:
- main  # This runs the pipeline when you push changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use a Microsoft-hosted Ubuntu machine

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet build --configuration Release
  displayName: 'Build the project'

- script: dotnet test
  displayName: 'Run tests'

- script: dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack the project'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact to Azure DevOps'
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'drop'
